spring:
  datasource:
    rul: jdbc:h2:~/jpashop;MVCC=TRUE
    username: ssafy
    password: ssafy!12
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug

